# Generated by Django 4.2.1 on 2023-05-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_contact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'is_correct')},
        ),
    ]
