# Generated by Django 4.2.1 on 2023-05-17 16:27

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=221, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=221, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=221, null=True, verbose_name='last_name')),
                ('image', models.ImageField(upload_to=apps.account.models.image_path)),
                ('bio', models.CharField(max_length=221)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super user')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff user')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active user')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
